let number1 = Math.floor(Math.random() * 100);
let number2 = Math.floor(Math.random() * 100);
let number3 = Math.floor(Math.random() * 100);
let number4 = Math.floor(Math.random() * 100);
let number5 = Math.floor(Math.random() * 100);
let sum = (number1 + number2 + number3 + number4 + number5);
let average = sum/5;
console.log( number1 + ", " + number2 + ", " + number3 + ", " + number4 + ", "+number5);
console.log("SUM= " + sum);
console.log("Average= " +average);